"""add order_inquiries table

Revision ID: eba077e6ae0e
Revises: c14e723f42a1
Create Date: 2026-02-11 16:13:01.726744+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eba077e6ae0e"
down_revision: str | None = "c14e723f42a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_inquiries",
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("customer_email", sa.String(length=255), nullable=True),
        sa.Column("order_number", sa.String(length=100), nullable=True),
        sa.Column(
            "inquiry_type",
            sa.Enum(
                "order_status",
                "tracking",
                "delivery_eta",
                "missing_package",
                "other",
                name="inquiry_type",
            ),
            nullable=False,
        ),
        sa.Column("order_status", sa.String(length=50), nullable=True),
        sa.Column("fulfillment_status", sa.String(length=50), nullable=True),
        sa.Column(
            "resolution",
            sa.Enum(
                "answered",
                "tracking_provided",
                "escalated",
                "unresolved",
                "verification_failed",
                name="inquiry_resolution",
            ),
            nullable=True,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_order_inquiries_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_order_inquiries_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_inquiries")),
    )
    op.create_index(
        op.f("ix_order_inquiries_conversation_id"),
        "order_inquiries",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_inquiries_order_number"), "order_inquiries", ["order_number"], unique=False
    )
    op.create_index(
        op.f("ix_order_inquiries_store_id"), "order_inquiries", ["store_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_inquiries_store_id"), table_name="order_inquiries")
    op.drop_index(op.f("ix_order_inquiries_order_number"), table_name="order_inquiries")
    op.drop_index(op.f("ix_order_inquiries_conversation_id"), table_name="order_inquiries")
    op.drop_table("order_inquiries")
    sa.Enum(name="inquiry_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="inquiry_resolution").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
