"""better_auth_migration

Revision ID: 002
Revises: 001
Create Date: 2026-01-29 11:47:16.263151+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: str | None = "001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_settings",
        sa.Column("organization_id", sa.String(length=255), nullable=False),
        sa.Column("shopify_domain", sa.String(length=255), nullable=False),
        sa.Column("shopify_access_token", sa.Text(), nullable=True),
        sa.Column("shop_name", sa.String(length=255), nullable=True),
        sa.Column("shop_email", sa.String(length=255), nullable=True),
        sa.Column("plan", sa.String(length=50), server_default="free", nullable=False),
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shop_settings")),
    )
    op.create_index(
        op.f("ix_shop_settings_organization_id"), "shop_settings", ["organization_id"], unique=True
    )
    op.create_index(
        op.f("ix_shop_settings_shopify_domain"), "shop_settings", ["shopify_domain"], unique=True
    )
    op.drop_index(op.f("ix_users_clerk_user_id"), table_name="users")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_table("users")
    # Drop foreign keys referencing organizations before dropping the table
    op.drop_constraint(
        op.f("fk_products_organization_id_organizations"), "products", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_knowledge_articles_organization_id_organizations"),
        "knowledge_articles",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_conversations_organization_id_organizations"), "conversations", type_="foreignkey"
    )
    op.drop_index(op.f("ix_organizations_shopify_domain"), table_name="organizations")
    op.drop_table("organizations")
    op.alter_column(
        "conversations",
        "organization_id",
        existing_type=sa.UUID(),
        type_=sa.String(length=255),
        existing_nullable=False,
        postgresql_using="organization_id::text",
    )
    op.alter_column(
        "knowledge_articles",
        "organization_id",
        existing_type=sa.UUID(),
        type_=sa.String(length=255),
        existing_nullable=False,
        postgresql_using="organization_id::text",
    )
    op.alter_column(
        "products",
        "organization_id",
        existing_type=sa.UUID(),
        type_=sa.String(length=255),
        existing_nullable=False,
        postgresql_using="organization_id::text",
    )
    op.create_index(
        op.f("ix_products_organization_id"), "products", ["organization_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_organization_id"), table_name="products")
    op.alter_column(
        "products",
        "organization_id",
        existing_type=sa.String(length=255),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="organization_id::uuid",
    )
    op.alter_column(
        "knowledge_articles",
        "organization_id",
        existing_type=sa.String(length=255),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="organization_id::uuid",
    )
    op.alter_column(
        "conversations",
        "organization_id",
        existing_type=sa.String(length=255),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="organization_id::uuid",
    )
    op.create_table(
        "organizations",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("shopify_domain", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("shopify_access_token", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("shop_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("shop_email", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "plan",
            sa.VARCHAR(length=50),
            server_default=sa.text("'free'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("shopify_domain", name=op.f("uq_organizations_shopify_domain")),
    )
    op.create_index(
        op.f("ix_organizations_shopify_domain"), "organizations", ["shopify_domain"], unique=False
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("clerk_user_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "role",
            postgresql.ENUM("owner", "admin", "member", name="user_role"),
            server_default=sa.text("'member'::user_role"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("clerk_user_id", name=op.f("uq_users_clerk_user_id")),
    )
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_index(op.f("ix_users_clerk_user_id"), "users", ["clerk_user_id"], unique=False)
    op.drop_index(op.f("ix_shop_settings_shopify_domain"), table_name="shop_settings")
    op.drop_index(op.f("ix_shop_settings_organization_id"), table_name="shop_settings")
    op.drop_table("shop_settings")
    # ### end Alembic commands ###
