"""Multi-store schema migration

Revision ID: 91c308d04d24
Revises: 002
Create Date: 2026-01-24 16:21:13.058021+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "91c308d04d24"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stores",
        sa.Column("organization_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("plan", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stores")),
    )
    op.create_index(op.f("ix_stores_organization_id"), "stores", ["organization_id"], unique=False)
    op.create_table(
        "store_integrations",
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum(
                "SHOPIFY", "WOOCOMMERCE", "BIGCOMMERCE", "MAGENTO", "CUSTOM", name="platform_type"
            ),
            nullable=False,
        ),
        sa.Column("platform_store_id", sa.String(length=255), nullable=False),
        sa.Column("platform_domain", sa.String(length=255), nullable=False),
        sa.Column("credentials", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACTIVE", "DISCONNECTED", "ERROR", name="integration_status"),
            nullable=False,
        ),
        sa.Column("status_message", sa.Text(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_store_integrations_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_integrations")),
    )
    op.create_index(
        op.f("ix_store_integrations_platform_domain"),
        "store_integrations",
        ["platform_domain"],
        unique=False,
    )
    op.create_index(
        op.f("ix_store_integrations_store_id"), "store_integrations", ["store_id"], unique=True
    )
    op.drop_index(op.f("ix_shop_settings_organization_id"), table_name="shop_settings")
    op.drop_index(op.f("ix_shop_settings_shopify_domain"), table_name="shop_settings")
    op.drop_table("shop_settings")
    op.add_column("conversations", sa.Column("store_id", sa.UUID(), nullable=False))
    op.alter_column(
        "conversations",
        "channel",
        existing_type=postgresql.ENUM("widget", "email", "whatsapp", "sms", name="channel"),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "conversations",
        "status",
        existing_type=postgresql.ENUM(
            "active", "resolved", "escalated", name="conversation_status"
        ),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "conversations",
        "extra_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "conversations", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False
    )
    op.drop_index(op.f("ix_conversations_organization_id"), table_name="conversations")
    op.create_index(op.f("ix_conversations_store_id"), "conversations", ["store_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_conversations_store_id_stores"),
        "conversations",
        "stores",
        ["store_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("conversations", "organization_id")
    op.add_column("knowledge_articles", sa.Column("store_id", sa.UUID(), nullable=False))
    op.alter_column(
        "knowledge_articles",
        "content_type",
        existing_type=postgresql.ENUM("faq", "policy", "guide", "page", name="content_type"),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_articles",
        "extra_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_articles",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_knowledge_articles_organization_id"), table_name="knowledge_articles")
    op.create_index(
        op.f("ix_knowledge_articles_store_id"), "knowledge_articles", ["store_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_knowledge_articles_store_id_stores"),
        "knowledge_articles",
        "stores",
        ["store_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("knowledge_articles", "organization_id")
    op.alter_column(
        "knowledge_chunks",
        "extra_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_chunks",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_knowledge_chunks_embedding"),
        table_name="knowledge_chunks",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.alter_column(
        "messages", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False
    )
    op.add_column("products", sa.Column("store_id", sa.UUID(), nullable=False))
    op.add_column(
        "products", sa.Column("platform_product_id", sa.String(length=255), nullable=False)
    )
    op.alter_column(
        "products",
        "status",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "tags",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "variants",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "images",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "products", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False
    )
    op.drop_index(
        op.f("ix_products_embedding"),
        table_name="products",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.drop_index(op.f("ix_products_organization_id"), table_name="products")
    op.drop_index(op.f("ix_products_organization_shopify_id"), table_name="products")
    op.create_index(op.f("ix_products_store_id"), "products", ["store_id"], unique=False)
    op.create_index(
        "ix_products_store_platform_id",
        "products",
        ["store_id", "platform_product_id"],
        unique=True,
    )
    op.create_foreign_key(
        op.f("fk_products_store_id_stores"),
        "products",
        "stores",
        ["store_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("products", "shopify_product_id")
    op.drop_column("products", "organization_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("organization_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.add_column(
        "products",
        sa.Column("shopify_product_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(op.f("fk_products_store_id_stores"), "products", type_="foreignkey")
    op.drop_index("ix_products_store_platform_id", table_name="products")
    op.drop_index(op.f("ix_products_store_id"), table_name="products")
    op.create_index(
        op.f("ix_products_organization_shopify_id"),
        "products",
        ["organization_id", "shopify_product_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_products_organization_id"), "products", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_products_embedding"),
        "products",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.alter_column(
        "products",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("uuid_generate_v4()"),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "images",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'[]'::jsonb"),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "variants",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'[]'::jsonb"),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "tags",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=sa.text("'{}'::character varying[]"),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "status",
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'active'::character varying"),
        existing_nullable=False,
    )
    op.drop_column("products", "platform_product_id")
    op.drop_column("products", "store_id")
    op.alter_column(
        "messages",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("uuid_generate_v4()"),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_knowledge_chunks_embedding"),
        "knowledge_chunks",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.alter_column(
        "knowledge_chunks",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("uuid_generate_v4()"),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_chunks",
        "extra_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        existing_nullable=False,
    )
    op.add_column(
        "knowledge_articles",
        sa.Column("organization_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_knowledge_articles_store_id_stores"), "knowledge_articles", type_="foreignkey"
    )
    op.drop_index(op.f("ix_knowledge_articles_store_id"), table_name="knowledge_articles")
    op.create_index(
        op.f("ix_knowledge_articles_organization_id"),
        "knowledge_articles",
        ["organization_id"],
        unique=False,
    )
    op.alter_column(
        "knowledge_articles",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("uuid_generate_v4()"),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_articles",
        "extra_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_articles",
        "content_type",
        existing_type=postgresql.ENUM("faq", "policy", "guide", "page", name="content_type"),
        server_default=sa.text("'faq'::content_type"),
        existing_nullable=False,
    )
    op.drop_column("knowledge_articles", "store_id")
    op.add_column(
        "conversations",
        sa.Column("organization_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_conversations_store_id_stores"), "conversations", type_="foreignkey"
    )
    op.drop_index(op.f("ix_conversations_store_id"), table_name="conversations")
    op.create_index(
        op.f("ix_conversations_organization_id"), "conversations", ["organization_id"], unique=False
    )
    op.alter_column(
        "conversations",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("uuid_generate_v4()"),
        existing_nullable=False,
    )
    op.alter_column(
        "conversations",
        "extra_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        existing_nullable=False,
    )
    op.alter_column(
        "conversations",
        "status",
        existing_type=postgresql.ENUM(
            "active", "resolved", "escalated", name="conversation_status"
        ),
        server_default=sa.text("'active'::conversation_status"),
        existing_nullable=False,
    )
    op.alter_column(
        "conversations",
        "channel",
        existing_type=postgresql.ENUM("widget", "email", "whatsapp", "sms", name="channel"),
        server_default=sa.text("'widget'::channel"),
        existing_nullable=False,
    )
    op.drop_column("conversations", "store_id")
    op.create_table(
        "shop_settings",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("organization_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("shopify_domain", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("shopify_access_token", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("shop_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("shop_email", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "plan",
            sa.VARCHAR(length=50),
            server_default=sa.text("'free'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shop_settings")),
        sa.UniqueConstraint(
            "organization_id",
            name=op.f("uq_shop_settings_organization_id"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "shopify_domain",
            name=op.f("uq_shop_settings_shopify_domain"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_shop_settings_shopify_domain"), "shop_settings", ["shopify_domain"], unique=False
    )
    op.create_index(
        op.f("ix_shop_settings_organization_id"), "shop_settings", ["organization_id"], unique=False
    )
    op.drop_index(op.f("ix_store_integrations_store_id"), table_name="store_integrations")
    op.drop_index(op.f("ix_store_integrations_platform_domain"), table_name="store_integrations")
    op.drop_table("store_integrations")
    op.drop_index(op.f("ix_stores_organization_id"), table_name="stores")
    op.drop_table("stores")
    # ### end Alembic commands ###
