"""add_cart_recovery_tables

Revision ID: a02a4cd25cdf
Revises: eba077e6ae0e
Create Date: 2026-02-14 16:18:28.679121+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a02a4cd25cdf"
down_revision: str | None = "eba077e6ae0e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "abandoned_checkouts",
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("shopify_checkout_id", sa.String(length=255), nullable=False),
        sa.Column("shopify_checkout_token", sa.String(length=255), nullable=True),
        sa.Column("customer_email", sa.String(length=255), nullable=True),
        sa.Column("customer_name", sa.String(length=255), nullable=True),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("line_items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checkout_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "abandoned", "recovered", "completed", name="checkout_status"),
            nullable=False,
        ),
        sa.Column("abandonment_detected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_order_id", sa.String(length=255), nullable=True),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_abandoned_checkouts_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_abandoned_checkouts")),
        sa.UniqueConstraint(
            "store_id", "shopify_checkout_id", name="uq_abandoned_checkouts_store_checkout"
        ),
    )
    op.create_index(
        op.f("ix_abandoned_checkouts_customer_email"),
        "abandoned_checkouts",
        ["customer_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_abandoned_checkouts_store_id"), "abandoned_checkouts", ["store_id"], unique=False
    )
    op.create_table(
        "email_unsubscribes",
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_email_unsubscribes_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_unsubscribes")),
        sa.UniqueConstraint("store_id", "email", name="uq_email_unsubscribes_store_email"),
    )
    op.create_index(
        op.f("ix_email_unsubscribes_store_id"), "email_unsubscribes", ["store_id"], unique=False
    )
    op.create_table(
        "recovery_sequences",
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("abandoned_checkout_id", sa.UUID(), nullable=False),
        sa.Column("customer_email", sa.String(length=255), nullable=False),
        sa.Column("sequence_type", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "completed", "stopped", name="sequence_status"),
            nullable=False,
        ),
        sa.Column("current_step_index", sa.Integer(), nullable=False),
        sa.Column("steps_completed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stopped_reason", sa.String(length=255), nullable=True),
        sa.Column("next_step_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["abandoned_checkout_id"],
            ["abandoned_checkouts.id"],
            name=op.f("fk_recovery_sequences_abandoned_checkout_id_abandoned_checkouts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_recovery_sequences_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_sequences")),
    )
    op.create_index(
        "ix_recovery_sequences_next_step_active",
        "recovery_sequences",
        ["next_step_at"],
        unique=False,
        postgresql_where="status = 'active'",
    )
    op.create_index(
        "ix_recovery_sequences_store_email",
        "recovery_sequences",
        ["store_id", "customer_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recovery_sequences_store_id"), "recovery_sequences", ["store_id"], unique=False
    )
    op.create_index(
        "ix_recovery_sequences_store_status",
        "recovery_sequences",
        ["store_id", "status"],
        unique=False,
    )
    op.create_table(
        "recovery_events",
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("sequence_id", sa.UUID(), nullable=True),
        sa.Column("abandoned_checkout_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("step_index", sa.Integer(), nullable=True),
        sa.Column("channel", sa.String(length=50), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["abandoned_checkout_id"],
            ["abandoned_checkouts.id"],
            name=op.f("fk_recovery_events_abandoned_checkout_id_abandoned_checkouts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sequence_id"],
            ["recovery_sequences.id"],
            name=op.f("fk_recovery_events_sequence_id_recovery_sequences"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_recovery_events_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_events")),
    )
    op.create_index(
        op.f("ix_recovery_events_event_type"), "recovery_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_recovery_events_sequence_id"), "recovery_events", ["sequence_id"], unique=False
    )
    op.create_index(
        op.f("ix_recovery_events_store_id"), "recovery_events", ["store_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recovery_events_store_id"), table_name="recovery_events")
    op.drop_index(op.f("ix_recovery_events_sequence_id"), table_name="recovery_events")
    op.drop_index(op.f("ix_recovery_events_event_type"), table_name="recovery_events")
    op.drop_table("recovery_events")
    op.drop_index("ix_recovery_sequences_store_status", table_name="recovery_sequences")
    op.drop_index(op.f("ix_recovery_sequences_store_id"), table_name="recovery_sequences")
    op.drop_index("ix_recovery_sequences_store_email", table_name="recovery_sequences")
    op.drop_index(
        "ix_recovery_sequences_next_step_active",
        table_name="recovery_sequences",
        postgresql_where="status = 'active'",
    )
    op.drop_table("recovery_sequences")
    op.drop_index(op.f("ix_email_unsubscribes_store_id"), table_name="email_unsubscribes")
    op.drop_table("email_unsubscribes")
    op.drop_index(op.f("ix_abandoned_checkouts_store_id"), table_name="abandoned_checkouts")
    op.drop_index(op.f("ix_abandoned_checkouts_customer_email"), table_name="abandoned_checkouts")
    op.drop_table("abandoned_checkouts")
    # ### end Alembic commands ###
