"""add_content_hash_and_search_indexes

Revision ID: c14e723f42a1
Revises: 73487033ba80
Create Date: 2026-02-02 11:22:02.195856+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c14e723f42a1"
down_revision: str | None = "73487033ba80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_conversations_customer_email"), "conversations", ["customer_email"], unique=False
    )
    op.add_column(
        "knowledge_articles", sa.Column("content_hash", sa.String(length=64), nullable=True)
    )
    op.create_index(
        op.f("ix_knowledge_articles_content_hash"),
        "knowledge_articles",
        ["content_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_knowledge_articles_content_hash"), table_name="knowledge_articles")
    op.drop_column("knowledge_articles", "content_hash")
    op.drop_index(op.f("ix_conversations_customer_email"), table_name="conversations")
    # ### end Alembic commands ###
